version: "3.6"
services:
  my-keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    restart: always
    container_name: "my-keycloak-container"
    command: "start-dev --import-realm"
    ports:
      - 8180:8180
    environment:
      KC_HTTP_PORT: "8180"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: "info"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    volumes:
      - ./realm:/opt/keycloak/data/import
    networks:
      - my-local-network

  my-redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    networks:
      - my-local-network

  my-nginx:
    image: nginx:1.23
    restart: always
    ports:
      - 8880:80
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - my-local-network

networks:
  my-local-network:
    driver: bridge
